services:
  frontend:
    build:
      context: .
      dockerfile: src/Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/jdmqa

  backend:
    build:
      context: .
      dockerfile: server/Dockerfile
    ports:
      - "3001:3001"
    depends_on:
      - db
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/jdmqa

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: jdmqa
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  pgdata: