name: Deploy to Staging

on:
  workflow_run:
    workflows: ["Enterprise QA Pipeline"]
    types:
      - completed
    branches: [develop]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  deploy_staging:
    name: Deploy to Staging Environment
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    environment: staging
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to staging
        run: |
          echo "🚀 Deploying to staging environment"
          echo "Image: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:develop"
          
      - name: Run smoke tests on staging
        run: |
          echo "🔍 Running smoke tests on staging"
          # Add staging smoke test commands here
          
      - name: Notify team
        uses: 8398a7/action-slack@v3
        with:
          status: success
          text: "✅ Successfully deployed to staging environment"
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
